name: pet_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  draggable_widget: ^2.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  flutter_bloc: ^8.1.3
  flutter_keyboard_visibility: ^6.0.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  ruler_scale_picker: ^0.1.0
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  stacked_card_carousel: ^0.0.4
  table_calendar: ^3.1.0
  wave: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sharedImages/settings/
    - assets/images/sharedImages/pets/dogs/
    - assets/images/lightImages/splash_screen/
    - assets/images/lightImages/profile/
    - assets/images/lightImages/profile/health/
    - assets/images/lightImages/profile/nutrition/
    - assets/images/lightImages/profile/activities/
    - assets/images/darkImages/splash_screen/
    - assets/images/darkImages/profile/
    - assets/images/darkImages/profile/health/
    - assets/images/darkImages/profile/nutrition/
    - assets/images/darkImages/profile/activities/
  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/catamaran/static/Catamaran-Thin.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-ExtraLight.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-Light.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-Regular.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-Medium.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-SemiBold.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-Bold.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-ExtraBold.ttf
        - asset: assets/fonts/catamaran/static/Catamaran-Black.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/notoSans/static/NotoSans-Thin.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-Light.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-Regular.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-Medium.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-SemiBold.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-Bold.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/notoSans/static/NotoSans-Black.ttf
