// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb7lONP87FcrkEUGN2ieZG8oHnCVBZCLE',
    appId: '1:196513145001:web:28d928a174bab670c689b8',
    messagingSenderId: '196513145001',
    projectId: 'pets-care-27f13',
    authDomain: 'pets-care-27f13.firebaseapp.com',
    storageBucket: 'pets-care-27f13.firebasestorage.app',
    measurementId: 'G-986E9XD226',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs4lu1k73xhRkkX3afNKH87EOuiRhdpZ4',
    appId: '1:196513145001:android:907158ed8f100723c689b8',
    messagingSenderId: '196513145001',
    projectId: 'pets-care-27f13',
    storageBucket: 'pets-care-27f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Bd9oV3eqh4GgTnnJ1JMQoeFzaZvARTs',
    appId: '1:196513145001:ios:fb7a7cc8d53b19e7c689b8',
    messagingSenderId: '196513145001',
    projectId: 'pets-care-27f13',
    storageBucket: 'pets-care-27f13.firebasestorage.app',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Bd9oV3eqh4GgTnnJ1JMQoeFzaZvARTs',
    appId: '1:196513145001:ios:fb7a7cc8d53b19e7c689b8',
    messagingSenderId: '196513145001',
    projectId: 'pets-care-27f13',
    storageBucket: 'pets-care-27f13.firebasestorage.app',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb7lONP87FcrkEUGN2ieZG8oHnCVBZCLE',
    appId: '1:196513145001:web:10e004289884b399c689b8',
    messagingSenderId: '196513145001',
    projectId: 'pets-care-27f13',
    authDomain: 'pets-care-27f13.firebaseapp.com',
    storageBucket: 'pets-care-27f13.firebasestorage.app',
    measurementId: 'G-J7L1PQ4C5F',
  );
}
